Update Filtering_pipeline

diff --git a/scripts/Filtering_pipeline b/scripts/Filtering_pipeline
--- a/scripts/Filtering_pipeline
+++ b/scripts/Filtering_pipeline
@@ -9,23 +9,34 @@ remove_temp=true
 PICARD=/pub64/mattm/apps/picard/build/libs/picard.jar
 RGID=E3modc
 RGLB=mod03
+logfile=Ah_mode_bamprep.log
+
+
 
 
 # Code
+
+# Set up log file
+
+exec 3>&1 1>"$logfile" 2>&1
+trap "echo 'ERROR: An error occurred during execution, check log $logfile for details.' >&3" ERR
+trap '{ set +x; } 2>/dev/null; echo -n "[$(date -Is)]  "; set -x' DEBUG
+set -e
+
+# Process bams
 
 mkdir -p $output
 
 for file in "$datapath"/*sort.bam; do 
 filename=${file##*/}
 filetag=$(basename "$filename" ".sort.bam")
-echo $filename
-echo $filetag
 
-sleep 5
 
-echo "adding read groups"
+echo "Moving to sample ${filetag}" | tee /dev/fd/3
 
-sleep 5
+sleep 3
+
+echo "Adding read groups" | tee /dev/fd/3
 
 java -jar $PICARD AddOrReplaceReadGroups \
 -I $file \
@@ -35,33 +46,29 @@ java -jar $PICARD AddOrReplaceReadGroups \
 -RGPL ILLUMINA -RGPU unit1 \
 -RGSM $filetag
 
-echo "filtering by flags"
+echo "Filtering by flags" | tee /dev/fd/3
 
 samtools view -@ 32 -b -f 3 -F 3852 "$output/${filetag}.RG.bam" -o "$output/${filetag}.filtered.bam"
 
-echo "sorting by name"
+echo "Sorting by name" | tee /dev/fd/3
 
 samtools sort -@ 32 -n "$output/${filetag}.filtered.bam" -o "$output/${filetag}.sorted.n.bam"
 
-echo "Adding mate score tag"
+echo "Adding mate score tag" | tee /dev/fd/3
 
 samtools fixmate -@ 32 -m "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam"
 
-echo "Sorting by position"
+echo "Sorting by position" | tee /dev/fd/3
 
 samtools sort -@ 32 "$output/${filetag}.fixmate.bam" -o "$output/${filetag}.sorted.p.bam"
 
-echo "removing duplicate reads"
+echo "Removing duplicate reads" | tee /dev/fd/3
 
 samtools markdup -r -@ 32 "$output/${filetag}.sorted.p.bam" "$output/${filetag}.markdup.bam"
 
-echo "indexing output bam"
+echo "Indexing output bam" | tee /dev/fd/3
 
 samtools index "$output/${filetag}.markdup.bam"
-
-echo "done"
-
-sleep 5
 
 if $remove_temp; then
   rm "$output/${filetag}.sorted.n.bam" "$output/${filetag}.fixmate.bam" "$output/${filetag}.sorted.p.bam" "$output/${filetag}.filtered.bam" "$output/${filetag}.RG.bam"
@@ -69,7 +76,7 @@ fi
 
 done
 
-
+echo "Finished!" | tee /dev/fd/3
 
 
 
